import sys
import os
import shutil

# Add the presentation_builder scripts path to sys.path to import ppt_template
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '.agents', 'skills', 'presentation_builder', 'scripts')))

from ppt_template import PresentationBuilder

def prepare_images():
    """
    Copies the generated images from the conversation brain directory to the workspace images directory.
    """
    print("Preparing image assets...")
    os.makedirs('images', exist_ok=True)
    
    # Absolute paths to the images generated by the generate_image tool
    images_to_copy = {
        r"C:\Users\coolexam\.gemini\antigravity\brain\46981e8b-847c-4739-be63-030458829c5c\device_design_1782263825599.png": "images/device_design.png",
        r"C:\Users\coolexam\.gemini\antigravity\brain\46981e8b-847c-4739-be63-030458829c5c\remedial_learning_1782263836069.png": "images/remedial_learning.png",
        r"C:\Users\coolexam\.gemini\antigravity\brain\46981e8b-847c-4739-be63-030458829c5c\community_story_1782263848978.png": "images/community_story.png"
    }
    
    for src, dst in images_to_copy.items():
        if os.path.exists(src):
            try:
                shutil.copy(src, dst)
                print(f"Successfully copied: {src} -> {dst}")
            except Exception as e:
                print(f"Error copying {src}: {e}")
        else:
            print(f"Warning: Source image not found at {src}")

def main():
    # 0. Copy generated images to workspace
    prepare_images()
    
    print("Initializing PresentationBuilder with 'navy' theme...")
    builder = PresentationBuilder(theme='navy')
    
    # 1. 封面投影片 (Cover) - Dark Navy
    print("Adding Slide 1: Cover...")
    builder.add_title_slide(
        title="說說學伴 (ShowShow Companion)",
        subtitle="突破偏鄉教育落差的無螢幕人本邊緣 AI 語音輔助系統"
    )
    
    # 2. 專案背景與問題意識 (Background) - Light
    print("Adding Slide 2: Background...")
    builder.add_content_slide(
        title="專案背景與教育平等的迫切性",
        points=[
            "教育是社會流動的基石：城鄉教育品質失衡將加劇社會階層固化，削弱國家整體競爭力。",
            "臺灣社會的多重結構性挑戰：超高齡化社會、偏鄉資源分配不均與雙語政策下的高齡與學童教育焦慮。",
            "大會晶創未來核心精神：引導跨領域團隊以人文社會思維洞察真實需求，結合前沿 AI 科技提出普惠方案。",
            "普惠科技的人本精神：優先考量弱勢群體的使用近便性，消除數位排斥，使科技真正成為教育平等的助力。"
        ]
    )
    
    # 3. 偏鄉雙語教育的三重困境 (Pain Points) - Light with Column Chart
    print("Adding Slide 3: Pain Points (with Native Chart)...")
    builder.add_chart_slide(
        title="偏鄉雙語教育的三重困境",
        chart_title="國中會考英語科待加強 (C) 比例比較",
        categories=["都會區平均", "偏鄉地區平均", "花蓮部分偏鄉"],
        series_name="英語科待加強 (C) 比例 (%)",
        series_data=[28.0, 47.0, 74.0],
        points=[
            "雙語政策下的「雙峰現象」：城鄉雙語資源嚴重失衡，學力差距持續擴大。",
            "師資流動率與短缺斷層：偏鄉常年招聘困難，代理教師比率高達 20%，學童常態性面臨每學期換老師困境。",
            "低成就學生的「習得性無助」：害怕發音不標準被同學嘲笑而在課堂沉默，且極度抗拒生硬的線上測驗介面。",
            "齊備硬體的應用真空：「生生用平板」已配發 61 萬台，但受限於斷網痛點，缺乏本地互動應用。"
        ]
    )
    
    # 4. 說說學伴：產品定位與設計理念 (Product Positioning) - Light Split
    print("Adding Slide 4: Product Positioning...")
    builder.add_split_slide(
        title="說說學伴：重新思考硬體形式與互動模式",
        left_title="傳統 App / 網頁學習平台",
        left_points=[
            "螢幕分心：學童容易被其他軟體或遊戲分散注意力",
            "學習焦慮：評量介面與分數回饋類似考試，引發心理壓力",
            "網路依賴：完全依賴穩定的網路連線，斷網時工具即失效",
            "數位鴻溝：需要複雜的觸控或輸入操作，使用門檻較高"
        ],
        right_title="說說學伴 (ShowShow Companion)",
        right_points=[
            "專注語音：無螢幕設計，引導學童完全專注於聽覺與口說",
            "有溫度的陪伴：如同與朋友聊天般輕鬆自然，重建學習自信",
            "自適應邊緣 AI：雙網混成推論，確保在偏鄉斷網時依舊可用",
            "說話即用：零門檻聲控互動，徹底消除弱勢群體的數位排斥"
        ]
    )
    
    # 5. 雙網混成推論架構 (Architecture) - Light
    print("Adding Slide 5: Architecture...")
    builder.add_content_slide(
        title="雙網混成推論架構 (Hybrid Edge-Cloud)",
        points=[
            "自適應切換機制：背景行程以每 5 秒一次的頻率 Ping 雲端節點，評估網路延遲與封包遺失率。",
            "雲端在線模式 (Cloud Mode)：網路正常時，語音特徵上載雲端，由 AWS Bedrock 提供高精度 RAG 檢索與對話。",
            "本地離線模式 (Edge Mode)：斷網時自動降級，關閉雲端上傳，所有運算完全在邊緣開發板 (Genio 520) 內處理。",
            "狀態切換指標：當延遲 > 800ms 或斷網 3 次時自動切換至離線；當延遲 < 300ms 且連線恢復時自動切換回雲端。",
            "遙測數據非同步同步：離線模式下的學童互動遙測數據快取至本地 SQLite，待網路恢復後非同步背景上載。"
        ]
    )
    
    # 6. 邊緣 NPU 軟硬體技術棧 (Edge Tech) - Light
    print("Adding Slide 6: Edge Tech Stack...")
    builder.add_content_slide(
        title="國產晶片與邊緣 AI 運算使能價值",
        points=[
            "國產智慧物聯網平台：採用聯發科技 Genio 520 (MT8365) 應用處理器，內建高效能 APU 提供本地 AI 算力。",
            "NeuroPilot 8 SDK 量化編譯：使用官方工具鏈將 PyTorch 模型量化壓制為 INT4/INT8，編譯為 NPU 可執行的 bin 檔。",
            "離線語音活動偵測 (VAD)：採用 WebRTC VAD（延遲 < 10ms），自適應音量門檻，過濾雜音以避免無效喚醒 NPU。",
            "離線語音識別與合成：Breeze-ASR/SenseVoice-Small（延遲 < 250ms）與 Piper TTS 引擎（首音延遲 < 150ms）。",
            "離線語言模型：Qwen3 1.7B / Qwen2.5 1.5B (INT4)，推論速度 > 18 tokens/sec，在本機即時執行鷹架引導。"
        ]
    )
    
    # 7. 雲端大腦與 RAG 教材串接 (Cloud RAG) - Light
    print("Adding Slide 7: Cloud RAG...")
    builder.add_content_slide(
        title="雲端大腦與多源教材向量檢索庫",
        points=[
            "高精度對話核心：使用 AWS Bedrock 的 Claude 3.5 Sonnet 模型，負責學童口說語意分析與診斷。",
            "日常對話陪伴核心：使用 Llama 3.1 70B 模型，負責高吞吐的對話預處理與基礎日常對話陪伴。",
            "三源教材向量檢索庫 (RAG)：整合教育部 Cool English（字彙口說）、均一（知識圖譜）、國教院（課綱對齊）。",
            "鷹架語音輸出：透過向量檢索，將契合臺灣課綱的單元教材與 Prompt 合併，提供針對性輔導。",
            "反思教學 AI 助教：將學童口說轉譯文本寫入 RDS PostgreSQL，異步生成學習弱點分析與差異化指引。"
        ]
    )
    
    # 8. 鷹架式引導與互動機制 (Pedagogy) - Light
    print("Adding Slide 8: Pedagogy...")
    builder.add_content_slide(
        title="鷹架引導與學童主動互動機制",
        points=[
            "鷹架引導理論 (Scaffolding)：允許學童中英夾雜輸入（如「我想吃 apple」），由 AI 溫和引導正確句型。",
            "不糾正、重引導：AI 不指出錯誤，而是以正面鼓勵語氣示範正確用法（如「跟著我說：I want to eat an apple」）。",
            "主動式聊天 (Proactive)：擺脫被動問答，依學習紀錄主動啟動話題，並內建 Minecraft、動漫等感興趣主題。",
            "遊戲化挑戰 (Fast, Fun, Fair)：設計 2-3 分鐘短任務、挑戰成功音效與虛擬徽章、本地公正星等發音評級。",
            "防沉迷休息機制 (Time-Out)：單次使用時限 25-30 分鐘，AI 擬人化宣告「沒電想睡覺」並自動休眠。"
        ]
    )
    
    # 9. 科技酷玩：外觀美學與情緒生命感 (Aesthetics) - Light with Image
    print("Adding Slide 9: Aesthetics (with Device Image)...")
    builder.add_image_slide(
        title="科技酷玩：外觀設計與情緒生命感",
        image_path="images/device_design.png",
        points=[
            "視覺風格：擺脫幼稚低齡玩具感，採用簡約幾何線條與低飽和度配色（如石墨灰），營造智慧潮玩酷炫感。",
            "個性化定製：提供磁吸配件（如耳朵/天線）與客製化防水貼紙，滿足 8-12 歲學童展現個性的心理需求。",
            "雙材質拼接：底座採用溫暖天然木質，機身主體包覆防摔親膚矽膠，讓學童抱在懷中感到放鬆與安全。",
            "LED 情緒呼吸光環：頂端多色彩呼吸燈展現情緒生命感（綠色代表傾聽、黃色代表思考、漸變代表挑戰成功）。",
            "聽覺專注：以富有生機的光效代替冰冷刺眼的液晶螢幕，引導學童將注意力完全集中於聽覺與口說互動。"
        ]
    )
    
    # 10. 應用情境一：無壓力學扶伴讀 (Scenario 1) - Light with Image
    print("Adding Slide 10: Scenario 1 (with Classroom Image)...")
    builder.add_image_slide(
        title="應用情境一：學扶課堂的無壓力伴讀鷹架",
        image_path="images/remedial_learning.png",
        points=[
            "無壓力練習：學童抱著物理裝置，沒有螢幕與分數壓力，如同朋友般一對一進行溫馨口說練習。",
            "100% 本地隱私保護：所有語音資料於晶片內即時處理完畢，提供最高規格個資保障，消除學校與家長疑慮。",
            "零延遲發音評測：不依賴網路，提供本機微秒級發音與跟讀反饋，消除偏鄉網路不穩帶來的卡頓挫折。",
            "教師差異化教學：AI 助教自動分析口說文本，為教師生成班級學習進度與發音弱點報表，減輕行政負擔。"
        ]
    )
    
    # 11. 應用情境二：跨世代社區共創 (Scenario 2) - Light with Image
    print("Adding Slide 11: Scenario 2 (with Community Image)...")
    builder.add_image_slide(
        title="應用情境二：跨世代美濃社區共創",
        image_path="images/community_story.png",
        points=[
            "跨世代在地記憶：長者以客語或國語講述菸樓歷史與回憶，學伴本地語音採集並過濾噪音。",
            "雲端 AI 翻譯重構：語音上傳至 AWS 雲端，由 AI 翻譯並重構為生動的雙語（中英）故事大綱與句型。",
            "學童英語改寫：學童在學伴的鷹架引導下，嘗試用簡單英文改寫阿嬤的故事，學伴提供即時詞彙修正與輔導。",
            "AI 雙語有聲繪本：最終產出專屬繪本，記錄長者回憶延緩老化，同時記錄學童的真實學習與在地文化歷程。",
            "城鄉永續價值：英語不再是冰冷的考試科目，而是有溫度的文化傳承工具，實踐跨世代共融深意。"
        ]
    )
    
    # 12. 結論與未來展望 (Conclusion/Thank You) - Dark Navy
    print("Adding Slide 12: Conclusion...")
    builder.add_title_slide(
        title="結論與展望：每個孩子都值得有人陪他開口",
        subtitle="結合國產晶片與雲端大腦，讓科技回歸人本初心，攜手彌平城鄉教育落差。 謝謝聆聽！"
    )
    
    # Save the presentation in the workspace root
    output_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "說說學伴專案簡報.pptx"))
    print(f"Saving final presentation to {output_path}...")
    builder.save(output_path)
    print("Final 12-page presentation generated successfully.")

if __name__ == "__main__":
    main()
